<!DOCTYPE html>
<html class=home lang="en">
<head>     
  <meta charset="utf-8">   
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">   
  <title>$pagetitle$</title> 
  <link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" title="Main CSS"> 
  <script src="/js/modernizr-1.6.min.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>
<div id="wrapper">
  <header>    	  
		<nav>$nav$</nav>	
  </header>		
	<section>$contents$</section>
</div>
$includes/analytics()$
</body>
</html>

