#!/bin/bash
set -euxo pipefail

# Fix the content type for all static files that do not have an extension,
# by finding them and setting the content type explicitly to 'text/html'
# to the corresponding object in S3.

find public -type f ! -name "*.*" -printf '%P\n' | \
  xargs -n 1 -I% aws s3 cp --content-type 'text/html' \
  "s3://www.deepakjois.name/%" "s3://www.deepakjois.name/%" \
  --metadata-directive REPLACE
