#!/bin/sh
link_file="data/links/`date '+%Y-%m.json'`"
if [ ! -e $link_file ]
then
  echo "[]" >> $link_file
fi
cat $link_file | jq  ". |= . + [{ \"link\": \"$1\", \"title\": \"$2\"}]" | sponge $link_file

