<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<title>$pagetitle$</title> 
<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" title="Main CSS"> 
</head>
<body>
<div id="wrapper">  
    	<header>
			<h1>Deepak Jois</h1>
  		<nav>
  			$nav$
  		</nav>				
		</header>		
	 $contents$
</div>
$analytics()$
</body>
</html>

