<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<title>$pagetitle$</title> 
<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen" title="Main CSS"> 
$iehtml5()$
</head>
<body>
<div id="wrapper">
  <header>    	  
	  <nav><a class="title" href="/">&#x2039; Home</a></nav>
			<h1>$pagetitle$</h1>

		<nav>
			$nav$
		</nav>	
  </header>		
	<section>
  $contents$
  </section>
</div>
</body>
</html>

