A curated collection of technical resources, mostly academic papers in the
field of computer science. I have restricted the resources to either stuff
that I have already read, or has been recommended by sources I trust. I
plan to keep these pages updated as I read more.

Mail me at <a href="mailto:&#100;&#101;&#101;&#112;&#097;&#107;&#046;&#106;&#111;&#105;&#115;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;">&#100;&#101;&#101;&#112;&#097;&#107;&#046;&#106;&#111;&#105;&#115;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;</a> if you have any suggestions.

* [Computer Systems – Reading List][computer-systems-reading]
* Programming Languages and Algorithms – Reading List _(coming soon)_
* [Logbook][logbook] – A logbook of random stuff relating to hacking code.

[computer-systems-reading]: /learning/computer-systems-reading.html
[programming-algo-reading]: /learning/programming-algo-reading.html
[logbook]: /learning/logbook.html