## Books
* [Computer Systems: A Programmer's Perspective, Second Edition](http://csapp.cs.cmu.edu/) by Randal E. Bryant and David R. O'Hallaron
* [Java Concurrency in Practice](http://www.javaconcurrencyinpractice.com/) by Brian Goetz, Tim Peierls, Joshua Bloch, Joseph Bowbeer, David Holmes, Doug Lea

## Internet
* [You Can't Sacrifice Partition Tolerance](http://codahale.com/you-cant-sacrifice-partition-tolerance/)
* [The problems with ACID, and how to fix them without going NoSQL](http://dbmsmusings.blogspot.com/2010/08/problems-with-acid-and-how-to-fix-them.html)
* [On Building a Stupidly Fast Graph Database](http://blog.directededge.com/2009/02/27/on-building-a-stupidly-fast-graph-database/)
* [SPDY: An experimental protocol for a faster web](http://www.chromium.org/spdy/spdy-whitepaper)
* [TCP and the Lower Bound of Web Performance](http://en.oreilly.com/velocity2010/public/schedule/detail/11792)

## Academic Papers

$papers:{ 
  it | * <a href="$it.url$" target="_new">$it.title$.</a> $it.authors$. $it.published$
}$

