## Books
* Structure and Interpretation of Computer Programs
* Real World Haskell
* Javascript: The Good Parts
* A Practical Guide to Data Structures and Algorithms using Java by Sally A. Goldman and Kenneth J. Goldman
* Coders at Work
* Introduction to Algorithms
* Dreaming in Code by Scott Rosenberg

## Internet

## Academic Papers

$papers:{ 
  it | * <a href="$it.url$" target="_new">$it.title$.</a> $it.authors$. $it.published$
}$

